export default {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  REQUEST_TODOS: 'REQUEST_TODOS',
  RECEIVE_TODOS: 'RECEIVE_TODOS',
  DELETE_TODO: 'DELETE_TODO',
  CURRENT_TODO_CHANGE: 'CURRENT_TODO_CHANGE',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE'
};