export default {
  ADD_TODO: 'ADD_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  FETCH_TODOS_REQUEST: 'FETCH_TODOS_REQUEST',
  FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
  FETCH_TODOS_FAILURE: 'FETCH_TODOS_FAILURE',
  RECEIVE_TODOS: 'RECEIVE_TODOS',
  DELETE_TODO: 'DELETE_TODO',
  CURRENT_TODO_CHANGE: 'CURRENT_TODO_CHANGE',
  SHOW_ERROR_MESSAGE: 'SHOW_ERROR_MESSAGE'
};